baseURL = "https://www.lasnotasdevero.com/"
languageCode = 'es'
title = 'Las Notas de Vero'
theme = 'vero'

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark]
    [markup.goldmark.parser]
      attribute = true     # ¡ojo aquí!
    [markup.goldmark.renderer]
      unsafe    = true     # para que acepte HTML